"""add archived_at field to projects

Revision ID: 4dc5e7d30bd7
Revises: 6406458610a7
Create Date: 2026-01-20 10:25:07.278186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc5e7d30bd7'
down_revision: Union[str, Sequence[str], None] = '6406458610a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'archived_at')
    # ### end Alembic commands ###
