"""add sync_logs and sync_conflicts tables

Revision ID: 8078b0cc8041
Revises: 4dc5e7d30bd7
Create Date: 2026-01-22 16:42:43.281495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8078b0cc8041'
down_revision: Union[str, Sequence[str], None] = '4dc5e7d30bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.Enum('IMPORT', 'EXPORT', 'FULL', name='synctype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='syncstatus', native_enum=False), nullable=False),
    sa.Column('source_file', sa.String(length=1000), nullable=True),
    sa.Column('tasks_created', sa.Integer(), nullable=False),
    sa.Column('tasks_updated', sa.Integer(), nullable=False),
    sa.Column('tasks_skipped', sa.Integer(), nullable=False),
    sa.Column('conflicts_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_log_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('obsidian_path', sa.String(length=1000), nullable=False),
    sa.Column('obsidian_line', sa.Integer(), nullable=False),
    sa.Column('obsidian_title', sa.String(length=500), nullable=False),
    sa.Column('obsidian_status', sa.String(length=50), nullable=False),
    sa.Column('obsidian_due_date', sa.Date(), nullable=True),
    sa.Column('obsidian_priority', sa.String(length=20), nullable=False),
    sa.Column('obsidian_modified', sa.DateTime(), nullable=False),
    sa.Column('obsidian_raw_line', sa.Text(), nullable=True),
    sa.Column('db_title', sa.String(length=500), nullable=True),
    sa.Column('db_status', sa.String(length=50), nullable=True),
    sa.Column('db_due_date', sa.Date(), nullable=True),
    sa.Column('db_priority', sa.String(length=20), nullable=True),
    sa.Column('db_modified', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.Enum('OBSIDIAN', 'DATABASE', 'SKIP', 'MANUAL', name='conflictresolution', native_enum=False), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sync_log_id'], ['sync_logs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_conflicts')
    op.drop_table('sync_logs')
    # ### end Alembic commands ###
